[project]
name = "reynolds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pyclearpass>=1.0.7",
    "pydantic-settings>=2.10.1",
    "rich>=14.1.0",
]
